apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress/
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: media-app-ingress
    path: ingress-patch.yaml

# k8s/overlays/staging/ingress/kustomization.yaml