apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/redis/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
    path: redis-deployment-patch.yaml

commonLabels:
  app.kubernetes.io/instance: web-app-redis
  app.kubernetes.io/component: cache
  role: cache
  db: redis