apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: neo4j-logs-pvc
  name: neo4j-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

# k8s/base/database/db-neo4j/db-neo4j-logs-storage.yaml