apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-neo4j
  labels:
    app.kubernetes.io/name: "neo4j"
    app.kubernetes.io/component: "database"
    app.kubernetes.io/managed-by: "kustomize"
    app.kubernetes.io/environment: "development"
    app.kubernetes.io/team: "backend-team"
  annotations:
    description: "Neo4j graph database"
    version: "latest"
    operational-notes: "Development instance, not for production use"

spec:
  template:
    spec:
      containers:
      - name: db-neo4j
        ports:
        - containerPort: 7474
          hostPort: 7474
          protocol: TCP
        - containerPort: 7687
          hostPort: 7687
          protocol: TCP
          
# k8s/overlays/dev/database/db-neo4j/db-neo4j-deployment-patch.yaml 