apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: neo4j-data-pvc
  name: neo4j-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M


# k8s/base/database/db-neo4j/db-neo4j-data-storage.yaml