apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/db-neo4j/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: db-neo4j
    path: db-neo4j-deployment-patch.yaml


commonLabels:
  app.kubernetes.io/instance: web-app-neo4j
  app.kubernetes.io/component: database
  role: database
  db: neo4j

# k8s/overlays/dev/database/kustomization.yaml