apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/db-neo4j/
  - neo4j-data-pv.yaml
  - neo4j-logs-pv.yaml
patches:
  - path: db-neo4j-deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: db-neo4j
    
  - path: db-neo4j-data-storage-patch.yaml
    target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: neo4j-data-pvc
    
  - path: db-neo4j-logs-storage-patch.yaml
    target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: neo4j-logs-pvc
    
namespace: development


commonLabels:
  app.kubernetes.io/instance: web-app-neo4j
  app.kubernetes.io/component: database
  role: database
  db: neo4j

# k8s/overlays/dev/database/kustomization.yaml