apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app/

patches:
  - path: web-app-deployment-patch.yaml
    target:
      kind: Deployment
      name: web-app
  - path: web-app-service-patch.yaml
    target:
      kind: Service
      name: web-app-service

images:
  - name: web-app-image
    newName: web-app-image
    newTag: dev-0.0.1

commonLabels:
  app: web-app

# k8s/overlays/dev/app/kustomization.yaml