apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-app-pv
  labels:
    app: web-app-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 
    
# k8s/overlays/dev/app/web-app-pv.yaml