FROM jwilder/nginx-proxy:alpine

COPY entrypoint-nginx-proxy.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint-nginx-proxy.sh

ENTRYPOINT ["entrypoint-nginx-proxy.sh"]
CMD ["forego", "start", "-r"]

# Dockerfile.nginx-proxy