# Build stage
FROM python:3.10.4-slim-bullseye as builder

WORKDIR /code

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Final stage
FROM python:3.10.4-slim-bullseye

# Install system dependencies in the final image
RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat ffmpeg curl iputils-ping && \
    rm -rf /var/lib/apt/lists/*
# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
# Copy netcat, ffmpeg, and curl binaries (adjust paths as needed)
# COPY --from=builder /usr/bin/netcat /usr/bin/netcat
# COPY --from=builder /usr/bin/ffmpeg /usr/bin/ffmpeg
COPY --from=builder /usr/bin/curl /usr/bin/curl
# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1 \
    PYTHONDONTWRITEBYTECODE 1 \
    PYTHONUNBUFFERED 1

WORKDIR /code

# Copy project files
COPY . .
COPY deploy/scripts /code/deploy/scripts
RUN chmod +x /code/deploy/scripts/init-web-app.sh


# Command to run the application
CMD ["python", "/code/manage.py", "runserver", "0.0.0.0:8000"]

 # Dockerfile.dev

# /Users/mshittu/programming-projects/python/django/media-be/Dockerfile.dev