apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: media-app-development
build:
  artifacts:
    - image: web-app-image
      context: /Users/mshittu/programming-projects/python/django/media-be/
      custom:
        buildCommand: docker buildx build --platform linux/arm64 -t $IMAGE -f Dockerfile.dev . --load
        # buildCommand: docker buildx build --platform linux/arm64 -t web-app-image:0.0.1 -f Dockerfile.dev . --load
    - image: frontend-app-image
      context: /Users/mshittu/programming-projects/javascript/react/media-fe/
      custom:
        buildCommand: docker buildx build --platform linux/arm64 -t $IMAGE -f Dockerfile.dev . --load
        # buildCommand: docker buildx build --platform linux/arm64 -t frontend-app-image:0.0.1 -f Dockerfile.dev . --load
  tagPolicy:
    envTemplate:
      template: '{{.ENV.VERSION}}-{{.GIT_COMMIT}}'

manifests:
  rawYaml:
    # Databases
    - /Users/mshittu/programming-projects/python/django/media-be/deploy/database/**/*.yaml

    # Apps
    - /Users/mshittu/programming-projects/python/django/media-be/deploy/app/*.yaml
    - /Users/mshittu/programming-projects/python/django/media-be/deploy/*.yaml
    - /Users/mshittu/programming-projects/javascript/react/media-fe/deploy/*.yaml

deploy:
  kubectl: {}

profiles:
  - name: database
    manifests:
      rawYaml:
        - /Users/mshittu/programming-projects/python/django/media-be/deploy/database/**/*.yaml
    deploy:
      kubectl: {}

      # kubectl:
      #   hooks:
      #     before:
      #       - host:
      #           command: ["sh", "-c", "echo Running the pre-deploy host hook running on $(hostname)!"]
      #       - host:
      #           command: ["kubectl", "apply", "-f", "/Users/mshittu/programming-projects/python/django/media-be/deploy/app/web-app-configmap.yaml"]
      #       - host:
      #           command: ["kubectl", "apply", "-f", "/Users/mshittu/programming-projects/python/django/media-be/deploy/app/web-app-secret.yaml"]


# skaffold.yaml