apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
spec:
  resources:
    requests:
      storage: "50M"  # Adjusted down from 500M based on usage analysis

# k8s/overlays/staging/database/db-neo4j/neo4j-pvc-data-patch.yaml