apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/redis/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
    path: redis-deployment-patch.yaml
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: redis-data
    path: redis-pvc-patch.yaml

commonLabels:
  app.kubernetes.io/instance: web-app-redis
  app.kubernetes.io/component: cache
  role: cache
  db: redis

# k8s/overlays/staging/database/redis/kustomization.yaml