apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"  # Reduced from 200Mi

# k8s/overlays/staging/database/redis/redis-pvc-patch.yaml