# Generated by Django 4.2.5 on 2023-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(choices=[('screen_reader', 'Screen Reader'), ('magnifier', 'Magnifier')], max_length=100)),
            ],
            options={
                'verbose_name': 'Accessibility Tool',
                'verbose_name_plural': 'Accessibility Tools',
            },
        ),
        migrations.CreateModel(
            name='StoryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('bookmark', 'Bookmark'), ('unbookmark', 'Unbookmark'), ('share', 'Share'), ('click_external', 'Click External Link'), ('view_storyline', 'View Storyline'), ('report', 'Report story'), ('highlight_text', 'Highlight Text')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Story Interaction',
                'verbose_name_plural': 'Stories Interactions',
            },
        ),
        migrations.CreateModel(
            name='StoryInteractionMetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('bookmark', 'Bookmark'), ('unbookmark', 'Unbookmark'), ('share', 'Share'), ('click_external', 'Click External Link'), ('view_storyline', 'View Storyline'), ('report', 'Report story'), ('highlight_text', 'Highlight Text')], max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Not Interested',
                'verbose_name_plural': 'Users Not Interested',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.UUIDField(unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
    ]
