# Generated by Django 4.2.5 on 2023-09-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(choices=[('screen_reader', 'Screen Reader'), ('magnifier', 'Magnifier')], max_length=100)),
            ],
            options={
                'verbose_name': 'Accessibility Tool',
                'verbose_name_plural': 'Accessibility Tools',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('screen_resolution', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('geolocation', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Locations Data',
            },
        ),
        migrations.CreateModel(
            name='ReferralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer_url', models.URLField()),
                ('search_terms', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deferral Data',
                'verbose_name_plural': 'Deferrals Data',
            },
        ),
        migrations.CreateModel(
            name='StoryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('bookmark', 'Bookmark'), ('unbookmark', 'Unbookmark'), ('share', 'Share'), ('click_external', 'Click External Link'), ('view_timeline', 'View Story Timeline')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Story Interaction',
                'verbose_name_plural': 'Stories Interactions',
            },
        ),
        migrations.CreateModel(
            name='UserNotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Not Interested',
                'verbose_name_plural': 'Users Not Interested',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(unique=True)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='analytics.devicedata')),
                ('location_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='analytics.locationdata')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
    ]
