# Generated by Django 4.2.5 on 2023-12-29 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.UUIDField(unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserNotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uninterested_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Not Interested',
                'verbose_name_plural': 'Users Not Interested',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryInteractionMetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('add-bookmark', 'Add Bookmark'), ('remove-bookmark', 'Remove Bookmark'), ('update-bookmark', 'Update Bookmark'), ('add-like', 'Add Like'), ('remove-like', 'Remove Like'), ('add-dislike', 'Add Dislike'), ('remove-dislike', 'Remove Dislike'), ('share', 'Share'), ('click_external', 'Click External Link'), ('view_storyline', 'View Storyline'), ('report', 'Report'), ('highlight_text', 'Highlight Text')], max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('schema', models.JSONField()),
            ],
            options={
                'unique_together': {('interaction_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='StoryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('add-bookmark', 'Add Bookmark'), ('remove-bookmark', 'Remove Bookmark'), ('update-bookmark', 'Update Bookmark'), ('add-like', 'Add Like'), ('remove-like', 'Remove Like'), ('add-dislike', 'Add Dislike'), ('remove-dislike', 'Remove Dislike'), ('share', 'Share'), ('click_external', 'Click External Link'), ('view_storyline', 'View Storyline'), ('report', 'Report'), ('highlight_text', 'Highlight Text')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_interactions', to=settings.AUTH_USER_MODEL)),
                ('user_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Story Interaction',
                'verbose_name_plural': 'Stories Interactions',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(choices=[('screen_reader', 'Screen Reader'), ('magnifier', 'Magnifier')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Tool',
                'verbose_name_plural': 'Accessibility Tools',
            },
        ),
    ]
