# Generated by Django 4.2.5 on 2023-09-19 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotinterested',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
        ),
        migrations.AddField(
            model_name='usernotinterested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uninterested_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyinteraction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='analytics.usersession'),
        ),
        migrations.AddField(
            model_name='storyinteraction',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referraldata',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_data', to='analytics.storyinteraction'),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to='analytics.storyinteraction'),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='analytics.storyinteraction'),
        ),
        migrations.AddField(
            model_name='accessibilitytool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
