# Generated by Django 4.2.5 on 2023-11-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_storyinteraction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyinteraction',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='analytics.usersession'),
        ),
    ]
