apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/celery/

patches:
  - path: celery-deployment-patch.yaml
    target:
      kind: Deployment
      name: celery

images:
  - name: web-app-image
    newName: europe-west2-docker.pkg.dev/media-app-418813/media-app-repo/web-app-image
    newTag: staging-0.0.1

commonLabels:
  app: celery

# k8s/overlays/staging/app/kustomization.yaml