project             = "media-app-v0-427519"
region              = "europe-west2"
credentials         = "../terraform-admin-service-key.json"
dns_zone_name       = "custom-domain-gong-ng"
dns_name            = "gong.ng."
compute_address_name = "media-be-ip"
cluster_name        = "gliese-autopilot-cluster"
artifact_registry_name = "media-app-repo"
terraform_service_account = "terraform-admin@media-app-v0-427519.iam.gserviceaccount.com"

