# Generated by Django 4.2.5 on 2023-11-23 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multimedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media_files/', validators=[multimedia.models.validate_file_size, multimedia.models.validate_file_extension])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio Note'), ('gif', 'GIF'), ('photo', 'Photo')], max_length=10)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Multimedia',
                'verbose_name_plural': 'Stories Multimedia',
            },
        ),
    ]
