# Generated by Django 4.2.5 on 2024-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
