apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-neo4j
  name: db-neo4j-service
spec:
  ports:
    - name: "7474"
      port: 7474
      targetPort: 7474
    - name: "7687"
      port: 7687
      targetPort: 7687
  selector:
    app: db-neo4j

# k8s/base/database/db-neo4j/db-neo4j-service.yaml