apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
  labels:
    app: neo4j-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" ## the volume is at /mnt/data on the cluster's node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: neo4j-data-pvc
  name: neo4j-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M


# k8s/base/database/db-neo4j/db-neo4j-data-storage.yaml