apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-neo4j
  name: db-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/password
          image: neo4j:latest
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
          name: db-neo4j
          ports:
            - containerPort: 7474
              hostPort: 7474
              protocol: TCP
            - containerPort: 7687
              hostPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: neo4j-data
            - mountPath: /logs
              name: neo4j-logs
      restartPolicy: Always
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
        - name: neo4j-logs
          persistentVolumeClaim:
            claimName: neo4j-logs-pvc

# k8s/base/database/db-neo4j/db-neo4j-deployment.yaml