namespace: staging

configMap:
  name: neo4j-config
  data:
    neo4j.conf: |
      dbms.default_listen_address=0.0.0.0
      dbms.default_advertised_address=db-neo4j-service
      dbms.connector.bolt.enabled=true
      dbms.connector.bolt.listen_address=0.0.0.0:7687
      dbms.connector.http.enabled=true
      dbms.connector.http.listen_address=0.0.0.0:7474
      dbms.security.auth_enabled=true

service:
  name: db-neo4j-service
  labels:
    app: db-neo4j
  ports:
    - name: "7474"
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: "7687"
      port: 7687
      targetPort: 7687
      protocol: TCP

statefulSet:
  name: db-neo4j
  replicas: 1
  image: neo4j:4.4.9-community
  volumeMounts:
    - name: neo4j-config-volume
      mountPath: /conf
  volumes:
    - name: neo4j-config-volume
      configMapName: neo4j-config
  volumeClaimTemplates:
    - name: neo4j-data
      accessModes: [ "ReadWriteOnce" ]
      storage: 1Gi
  secretName: web-app-secret
  env:
    - name: NEO4J_AUTH
      key: NEO4J_AUTH
    - name: NEO4J_USERNAME
      key: NEO4J_USERNAME
    - name: NEO4J_PASSWORD
      key: NEO4J_PASSWORD
