apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  labels:
    app: postgres-data-pv
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" ## the volume is at /mnt/data on the cluster's node

# k8s/overlays/dev/database/db-postgres/db-postgres-data-pv.yaml