apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/database/db-postgres/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: db-postgres
    path: db-postgres-deployment-patch.yaml

commonLabels:
  app.kubernetes.io/instance: web-app-postgres
  app.kubernetes.io/component: database
  role: database
  db: postgres