apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gong-ng-tls
spec:
  secretName: gong-ng
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: gong.ng
  dnsName:
    - gong.ng
    - www.gong.ng

    - api.dev.gong.ng
    - app.dev.gong.ng
    - www.api.dev.gong.ng
    - www.app.dev.gong.ng

    - api.staging.gong.ng
    - app.staging.gong.ng
    - www.api.staging.gong.ng
    - www.app.staging.gong.ng

    - api.prod.gong.ng
    - app.prod.gong.ng
    - www.api.prod.gong.ng
    - www.app.prod.gong.ng
  acme: 
    config:
      - http01:
          ingressClass: nginx
        domains:
          - gong.ng
          - www.gong.ng

# k8s/cluster-wide/certificate.yaml