apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-volume-pv
  labels:
    app: media-volume-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: media-volume
  name: media-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
