apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ toYaml .Values.service.labels | indent 4 }}
spec:
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app: db-neo4j
