apiVersion: v1
kind: Service
metadata:
  name: db-postgres-service
spec:
  selector:
    app: db-postgres
  # type: NodePort
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

# k8s/base/database/db-postgres/db-postgres-service.yaml