apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data-pvc
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

# k8s/base/database/db-postgres/db-postgres-data-storage.yaml