apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.webApp.name }}
  namespace: {{ .Values.namespace.name }}
  labels: 
  {{ toYaml .Values.deployment.webApp.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.webApp.replicas }}
  selector:
    matchLabels:
      app: web-app
      environment: staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-app
        environment: staging
    spec:
      containers:
      - name: web-app
        image: "{{ .Values.deployment.webApp.image.repository }}:{{ .Values.deployment.webApp.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.webApp.image.pullPolicy }}
        ports:
        {{- range .Values.deployment.webApp.ports }}
        - containerPort: {{ .containerPort }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.deployment.webApp.resources.limits.cpu }}
            memory: {{ .Values.deployment.webApp.resources.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.webApp.resources.requests.cpu }}
            memory: {{ .Values.deployment.webApp.resources.requests.memory }}
        envFrom:
{{- range .Values.deployment.webApp.envFrom }}
          {{- if .configMapRefName }}
          - configMapRef:
              name: {{ .configMapRefName }}
          {{- end }}
          {{- if .secretRefName }}
          - secretRef:
              name: {{ .secretRefName }}
          {{- end }}
{{- end }}
        volumes:
        - name: web-app-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}

# k8s/web-app/templates/deployment-web-app.yaml