apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: ClusterIP  # Changed from NodePort to ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000


# k8s/overlays/staging/app/web-app-service-patch.yaml