# ./k8s/overlays/staging/web-app-deployment-patch.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  template:
    spec:
      containers:
      - name: web-app

        # resources:
        #   requests:
        #     cpu: 250m  # Reduced from 500m
        #     memory: 256Mi
        #   limits:
        #     cpu: 500m  # Reduced if necessary
        #     memory: 512Mi

        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
        env:
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: DJANGO_ALLOWED_HOSTS

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: POSTGRES_PASSWORD


          - name: POSTGRES_DB
            value: "mediabedb"
          - name: POSTGRES_USER
            value: "mediabeuser"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            value: "db-postgres-postgresql"
          - name: POSTGRES_PORT
            value: "5432"

# k8s/overlays/staging/app/web-app-deployment-patch.yaml