apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # downgraded from 2Gi storage

# k8s/overlays/staging/app/web-app-pvc-patch.yaml