apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Use the Let's Encrypt staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mshittu.work@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx

# k8s/cluster-wide/cluster-issuer/cluster-issuer-staging.yaml