apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.celery.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
{{- toYaml .Values.deployment.celery.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.celery.replicas }}
  selector:
    matchLabels:
      app: celery
      environment: staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery
        environment: staging
    spec:
      containers:
      - name: celery
        image: "{{ .Values.shared.image.repository }}:{{ .Values.shared.image.tag }}"
        command:
{{- toYaml .Values.deployment.celery.command | nindent 8 }}
        {{- include "shared.resources" . | nindent 8 }}
        envFrom:
{{- include "shared.envFrom" . | nindent 8 }}
        {{- include "shared.volumeMounts" . | nindent 8 }}


# k8s/web-app/templates/deployment-celery.yaml