apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace.name }}
  labels: 
{{- toYaml .Values.pvc.labels | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  accessModes:
{{- toYaml .Values.pvc.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

# k8s/web-app/templates/pvc.yaml