from rest_framework.views import exception_handler
from rest_framework.response import Response
from rest_framework import status

def custom_exception_handler(exc, context):
    # Call DRF's default exception handler first to get the standard error response.
    response = exception_handler(exc, context)

    # If a response has been generated by the default handler, customize it.
    if response is not None:
        custom_response_data = {
            'status_code': response.status_code,
            'error': response.data
        }
        response.data = custom_response_data

    return response
