from rest_framework.views import exception_handler
from rest_framework.response import Response
from rest_framework import status

def custom_exception_handler(exc, context):
    # Call DRF's default exception handler first to get the standard error response.
    response = exception_handler(exc, context)

    # If a response has been generated by the default handler, customize it.
    if response is not None:
        # Check if the error is a dictionary with a single key 'detail'
        if 'detail' in response.data:
            error_detail = response.data.pop('detail')
            response.data = {'detail': [error_detail]}
        
        custom_response_data = {
            'status': 'failed',
            'status_code': response.status_code,
            'error': response.data
        }
        response.data = custom_response_data

    return response

# utils/handlers.py