apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    app: redis-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" ## the volume is at /mnt/data on the cluster's node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-data
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

# k8s/base/database/redis/redis-data-storage.yaml