apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-app-configmap.yaml
  - web-app-deployment.yaml
  - web-app-pvc.yaml
  - web-app-secret.yaml
  - web-app-service.yaml


# k8s/base/app/kustomization.yaml