apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: web-app-pvc
  name: web-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# k8s/base/app/web-app-pvc.yaml