# backend-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_NAME: 'Aproko'
  APP_CODE_NAME: 'media-be'
  APP_VERSION: '0.0.2'
  APP_DESCRIPTION: 'This is a brief description of the app.'
  APP_FRONTEND_DOMAIN: 'http://127.0.0.1:3000/'
  APP_BASE_URL: 'https://api.mediaapp.local'
  DJANGO_DEBUG: "True"
  APP_MEDIA_ENVIRONMENT: "development"
  APP_MEDIA_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  APP_MEDIA_EMAIL_HOST: "smtp.gmail.com"
  APP_MEDIA_EMAIL_USE_TLS: "True"
  APP_MEDIA_EMAIL_PORT: "587"
  APP_MEDIA_EMAIL_HOST_USER: "mshittu.work@gmail.com"
  APP_MEDIA_SENDGRID_API_KEY_NAME: "media-app-access"

  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

  POSTGRES_DB: "mediabedb"
  POSTGRES_USER: "mediabeuser"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"

  NEO4J_HOST: "myneo4j-service"
  NEO4J_PORT: "7687"

  CELERY_BROKER_URL: 'redis://redis-service:6379/0'
  CELERY_RESULT_BACKEND: 'redis://redis-service:6379/0'

# k8s-manifests/backend-config.yaml