apiVersion: batch/v1
kind: Job
metadata:
  name: backend-setup-job
spec:
  backoffLimit: 1  
  template:
    spec:
      containers:
      - name: django-setup
        securityContext:
          runAsUser: 1000 
        image: web-app-image:0.0.1
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Wait for PostgreSQL to be ready
          until PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c '\q'; do
            >&2 echo "Postgres is unavailable - sleeping"
            sleep 1
          done
          >&2 echo "Postgres is up - executing command"
          
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py autoseed &&
          # python manage.py install_labels &&
          python manage.py importstories &&
          echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('test@test.co', 'commonPassword=1')" | python manage.py shell
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
      restartPolicy: Never

# k8s-manifests/backend-setup-job.yaml