apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: backend-init
        image: web-app-image:0.0.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            python manage.py makemigrations &&
            python manage.py migrate
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
      containers:
      - name: backend
        image: web-app-image:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

# k8s-manifests/backend-deployment.yaml
