apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-deployment
  labels:
    namespace: "dev-deployment" 

resources:
  - mediaapp-local-certs-secret.yaml
  - postgres-storage.yaml
  - neo4j-storage.yaml
  - backend-secret.yaml
  - backend-config.yaml
  - neo4j-deployment.yaml
  - celery-deployment.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - backend-setup-job.yaml
  - media-pvc.yaml
  - backend-deployment.yaml
  - ingress.yaml
  # - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

# Include other directives as needed, such as commonLabels, commonAnnotations, etc.
# k8s-manifests/kustomization.yaml