apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-config.yaml
  - backend-deployment.yaml
  - backend-secret.yaml
  - backend-setup-job.yaml
  - celery-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - media-pvc.yaml
  - neo4j-config.yaml
  - neo4j-statefulset.yaml
  - mediaapp-local-certs-secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

# Include other directives as needed, such as commonLabels, commonAnnotations, etc.
# k8s-manifests/kustomization.yaml