apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
  labels:
    app: neo4j-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" ## the volume is at /mnt/data on the cluster's node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  labels:
    app: neo4j-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M

# k8s-manifests/neo4j-storage.yaml