apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app/
  - celery/
  - database/
  - ingress/
namespace: development

configMapGenerator:
  - name: web-app-configmap
    behavior: merge
    envs:
      - app/dev.properties
secretGenerator:
  - name: web-app-secret
    behavior: merge
    envs:
      - app/secrets.env
commonLabels:
  environment: development


# k8s/overlays/dev/kustomization.yaml