name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mediaapp:web-app-latest

      - name: Delete Old docker container for web app
        run: sudo docker compose -f docker-compose.staging.yml down web-app || true

      - name: Run Docker Container for web app
        run: sudo docker compose -f docker-compose.staging.yml up -d
