name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches:
      - staging
    types:
      - completed
  pull_request:
    branches:
      - staging
  workflow_dispatch:

env:
  DOCKER_INTERNAL_NETWORK_NAME: "my_media_network"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # Dynamically checkout the branch that triggered the workflow
      #   - name: Deploy to Staging
      #     run: |
      #         ./scripts/deploy_staging.sh
      #     shell: bash

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Create Docker network if not exists
        run: |
          if ! sudo docker network ls | grep -q ${{ env.DOCKER_INTERNAL_NETWORK_NAME }}; then
            sudo docker network create ${{ env.DOCKER_INTERNAL_NETWORK_NAME }};
          fi
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mediaapp:web-app-latest

      - name: Delete Old docker container for web app
        run: sudo docker compose -f docker-compose.staging.yml down web-app || true

      - name: Run Docker Container for web app
        run: sudo docker compose -f docker-compose.staging.yml up -d

      - name: Remove Untagged Docker Images
        run: |
          dangling_images=$(sudo docker images -f "dangling=true" -q)
          if [ -n "$dangling_images" ]; then
            sudo docker rmi $dangling_images
          else
            echo "No dangling images to remove"
          fi

# .github/workflows/cd-vm-deploy.yml
