name: Deploy to Staging on Compute Engine

on:
  # push:
  #   branches:
  #     - staging # Triggers the workflow on pushes to the staging branch
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub UI

env:
  GCP_REGION: ${{ secrets.GKE_REGION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
  DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

jobs:
  setup:
    name: Setup and Configure Environment
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mediaapp:web-app-latest

      - name: Delete Old docker container for web app
        run: sudo docker compose -f docker-compose.staging.yml down web-app || true

      - name: Run Docker Container for web app
        run: sudo docker compose -f docker-compose.staging.yml up -d
