name: Deploy to Staging on GKE

on:
  push:
    branches:
      - staging  # This specifies that the workflow only runs on the staging branch

  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/web-app-image:${{ github.sha }} -f Dockerfile.dev .


      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GKE_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev



      - name: Push Docker image to Google Artifact Registry
        run: docker push ${{ secrets.ARTIFACT_REGISTRY }}/web-app-image:${{ github.sha }}

      - name: List files in the k8s directory
        run: ls -R k8s/overlays/staging/app/
        working-directory: ${{ github.workspace }}

      # - name: Deploy to GKE
      #   run: |
      #     kubectl set image -f k8s/overlays/staging/app/web-app-deployment.yaml web-app=${{ secrets.ARTIFACT_REGISTRY }}/web-app-image:${{ github.sha }}
      #     kubectl apply -k k8s/overlays/staging/
      #   working-directory: ${{ github.workspace }}



      # - name: Generate kustomization for deployment
      #   run: |
      #     echo "images:" > ./k8s/overlays/staging/app/kustomize_override.yaml
      #     echo "  - name: web-app-image" >> ./k8s/overlays/staging/app/kustomize_override.yaml
      #     echo "    newName: ${{ secrets.ARTIFACT_REGISTRY }}/web-app-image" >> ./k8s/overlays/staging/app/kustomize_override.yaml
      #     echo "    newTag: ${{ github.sha }}" >> ./k8s/overlays/staging/app/kustomize_override.yaml
      #     cat ./k8s/overlays/staging/app/kustomize_override.yaml

      # - name: Deploy to GKE
      #   run: |
      #     kustomize build ./k8s/overlays/staging/app | kubectl apply -f -



      - name: Update Kustomize image tag
        run: |
          cd k8s/overlays/staging/app/
          kustomize edit set image web-app-image=${{ secrets.ARTIFACT_REGISTRY }}/web-app-image:${{ github.sha }}
          cat kustomization.yaml  # Display the file to verify changes


      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT }}
          kustomize build ./k8s/overlays/staging/app | kubectl apply -f -



            
      - name: Verify Deployment
        run: kubectl rollout status deployment/web-app-deployment


# .github/workflows/staging-deploy.yml