name: Deploy to Staging on GKE

on:
  push:
    branches:
      - staging  # This specifies that the workflow only runs on the staging branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/web-app:${{ github.sha }} -f Dockerfile.staging .

      - name: Push Docker image to Google Artifact Registry
        run: docker push ${{ secrets.ARTIFACT_REGISTRY }}/web-app:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          kubectl set image -f k8s/overlays/staging/app/web-app-deployment.yaml web-app=${{ secrets.ARTIFACT_REGISTRY }}/web-app:${{ github.sha }}
          kubectl apply -k k8s/overlays/staging/

      - name: Verify Deployment
        run: kubectl rollout status deployment/web-app-deployment
