apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - ../../cluster-wide/cluster-issuer/cluster-issuer-staging.yaml
  - app/
  - celery/
  - database/
  - ingress/
  # - certificates/
namespace: staging

configMapGenerator:
  - name: web-app-configmap
    behavior: merge
    envs:
      - app/staging.properties
# secretGenerator:
#   - name: web-app-secret
#     behavior: merge
#     envs:
#       - app/secrets.env
commonLabels:
  environment: staging


# k8s/overlays/staging/kustomization.yaml